version: '3'
services:
  server:
    image: flwr_server_keras
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    networks:
      - flower
  client:
    image: flwr_client_keras
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    networks:
      - flower
networks:
  flower: