version: '3'
services:
  server:
    image: flwr_server_keras
    volumes:
      - '<datset example: "\docker\fishdata.pkl">:/app'
    container_name: server
    networks:
      - flower
  client:
    image: flwr_client_keras
    volumes:
      - '<datset>:/app'
    container_name: client
    networks:
      - flower
networks:
  flower: